### PR TITLE
fix: improve scope handling

### LINKED ISSUE #794: [BUG] eww slowly fills ram
### Checklist before submitting an issue

- [X] I have searched through the existing [closed and open issues](https://github.com/elkowar/eww/issues?q=is%3Aissue) for eww and made sure this is not a duplicate
- [X] I have specifically verified that this bug is not a common [user error](https://github.com/elkowar/eww/issues?q=is%3Aissue+label%3Ano-actual-bug+is%3Aclosed)
- [X] I am providing as much relevant information as I am able to in this bug report (Minimal config to reproduce the issue for example, if applicable)

### Description of the bug

When I let eww run for a while I notice that it's slowly filling the ram. The speed it's filling the ram with seems to be dependent on how often defpolls are executed. This isn't caused by variables getting bigger, as they don't really change in terms of size.

### Reproducing the issue

Just create a lot of defpolls with very short intervals

### Expected behaviour

_No response_

### Additional context

`
(defvar app_menu_reveal "false")
(defvar power_menu_reveal "false")
(defvar show_apps "false")

(defvar reveal_app_terminal "false")
(defvar reveal_app_vscode "false")

(defvar ram_dropdown_reveal "false")
(defvar disk_dropdown_reveal "false")
(defvar cpu_dropdown_reveal "false")

(defpoll time
  :interval "0.5s"
  :initial ""
  'date "+%T"'
)

(defpoll cpu
  :interval "0.5s"
  '/home/finley/.config/eww/cpu.sh'
)

(defpoll root_percent
  :interval "1s"
  :initial ""
  '/home/finley/.config/eww/disk-percent.sh'
)

(defpoll disks
  :interval "1s"
  '/home/finley/.config/eww/disks.sh'
)

(defpoll proc
  :interval "0.5s"
  '/home/finley/.config/eww/proc.sh'
)

(defpoll hypr
  :interval "0.5s"
  '/home/finley/.config/eww/hypr.sh'
)

(defpoll apps
  :interval "1000s"
  'cat /home/finley/.config/eww/apps.json'
)

(defpoll volume
  :interval "0.1s"
  `pactl list sinks | grep 'Volume: front-left' | awk '{print $5}' | sed 's/%//' | head -n 1`
)

(include "/home/finley/.config/eww/variables.yuck")

(defwidget volume []
  (box
    :class "volume_box"
    :space-evenly false
    :spacing 5;
    (scale
      :class "volume"
      :orientation "h"
      :width "200"
      :min 0
      :max 100
      :value "${volume}"
      :draw-value false
      :onchange "/home/finley/.config/eww/volume-change.sh {}"
    )
    (box
      :class "volume_buttons"
      (eventbox
        :onclick ``
        (label
          :class "volume_buttons_label"
          :text "+"
        )
      )
      (eventbox
        :onclick ``
        (label
          :class "volume_buttons_label"
          :text "-"
        )
      )
    )
  )
)

(defwidget pie_chart [val icon name]
  (box
    :spacing 0
    :class "${name}"
    (circular-progress
      :start-at "75"
      :clockwise true
      :thickness 15
      :value "${val}"
    )
    (label
      :text "${icon} "
    )
  )
)

(defwidget cpu []
  (eventbox
    :onhover "${EWW_CMD} update cpu_dropdown_reveal=true"
    :onhoverlost "${EWW_CMD} update cpu_dropdown_reveal=false"
    (pie_chart
      :val "${cpu}"
      :icon ""
      :name "cpu"
    )
  )
)

(defwidget ram []
  (eventbox
    :onhover "${EWW_CMD} update ram_dropdown_reveal=true"
    :onhoverlost "${EWW_CMD} update ram_dropdown_reveal=false"
    (pie_chart
      :val "${EWW_RAM.used_mem_perc}"
      :icon ""
      :name "ram"
    )
  )
)

(defwidget disk []
  (eventbox
    :onhover "${EWW_CMD} update disk_dropdown_reveal=true"
    :onhoverlost "${EWW_CMD} update disk_dropdown_reveal=false"
    (pie_chart
      :val "${round(root_percent, 1)}"
      :icon ""
      :name "disk"
    )
  )
)

(defwidget app_menu_item [icon command class]
  (eventbox
    :onclick "${command}"
    (label
      :class "${class}"
      :text "${icon}"
    )
  )
)

(defwidget app_menu_v2 [apps]
  (eventbox
    :onhover "${EWW_CMD} update show_apps=true"
    :onhoverlost "${EWW_CMD} update show_apps=false"
    (box
      :class "app_menu"
      :space-evenly false
      (image
        :path "${EWW_CONFIG_DIR}/apps.png"
      )
      (revealer
        :reveal "${show_apps}"
        :transition "slideleft"
        :duration "0.1s"
        (box
          :spacing 0
          :hexpand false
          (for item in apps
            (eventbox
              :onclick "bash -c '${item.command} & disown $(jobs -lp)'"
              (image
                :path "${item.icon}"
                :class "app_menu_item"
              )
            )
          )
        )
      )
    )
  )
)

(defwidget power_menu []
  (eventbox
    :onhover "${EWW_CMD} update power_menu_reveal=true"
    :onhoverlost "${EWW_CMD} update power_menu_reveal=false"
    (box
      :class "power_menu"
      :spacing 10
      :space-evenly false
      (revealer
        :transition "slideleft"
        :reveal "${power_menu_reveal}"
        :duration "200ms"
        (box
          :spacing 15
          :space-evenly false
          (label)
          (app_menu_item
            :icon ""
            :command "reboot"
            :class "power_menu_reboot"
          )
        )
      )
      (app_menu_item
            :icon ""
            :command "shutdown"
            :class "power_menu_shutdown"
      )
    )
  )
)

(defwidget clock []
  (box
    :class "clock_box"
    (label
      :class "clock"
      :text "${time}"
    )
  )
)

(defwidget cpu_dropdown []
  (revealer
    :reveal "${cpu_dropdown_reveal}"
    :transition "slideleft"
    :visible "${cpu_dropdown_reveal}"
    (box
      :class "cpu_dropdown"
      :orientation "vertical"
      :spacing 5
      ;(for obj in proc
      ;  (box
      ;    :class "cpu_dropdown_entry"
      ;    (label
      ;      :halign "start"
      ;      :class "cpu_dropdown_name"
      ;      :text "${obj.command}"
      ;    )
      ;    (label
      ;      :halign "end"
      ;      :class "cpu_dropdown_usage"
      ;      :text "${obj.cpu_percent}"
      ;    )
      ;  )
      ;)
    )
  )
)

(defwidget ram_dropdown []
  (revealer
    :reveal "${ram_dropdown_reveal}"
    :transition "slideleft"
    :visible "${ram_dropdown_reveal}"
    (box
      :spacing 0
      :class "ram_dropdown"
      :orientation "vertical"
      (label
        :halign "start"
        :text "total: ${round(EWW_RAM.total_mem / 1024 / 1024 /1024, 1)}gb"
        :class "ram_dropdown_text"
      )
      (label
        :halign "start"
        :text "used: ${round(EWW_RAM.used_mem / 1024 / 1024 /1024, 1)}gb"
        :class "ram_dropdown_text"
      )
      (label
        :halign "start"
        :text "free: ${round(EWW_RAM.free_mem / 1024 / 1024 /1024, 1)}gb"
        :class "ram_dropdown_text"
      )
    )
  )
)

(defwidget disk_dropdown []
  (revealer
    :reveal "${disk_dropdown_reveal}"
    :transition "slideleft"
    :visible "${disk_dropdown_reveal}"
    (box
      :space-evenly false
      :spacing 5
      :class "disk_dropdown"
      :orientation "vertical"
      :vexpand "false"
      (for obj in disks
        (box
          :space-evenly false
          :vexpand "false"
          :orientation "vertical"
          :spacing 2
          (label
            :class "disk_dropdown_name"
            :halign "start"
            :text "${obj.mount}"
          )
          (progress
            :class "disk_dropdown_progress"
            :orientation "horizontal"
            :value "${obj.used_perc}"
            :vexpand true
            :hexpand true
          )
          (box
            :spacing 0
            :orientation "vertical"
            :class "disk_dropdown_values"
            (box
              (label
                :class "disk_dropdown_text"
                :halign "start"
                :text "total:"
              )
              (label
                :class "disk_dropdown_text"
                :halign "end"
                :text "${obj.total}"
              )
            )
            (box
              (label
                :class "disk_dropdown_text"
                :halign "start"
                :text "used:"
              )
              (label
                :class "disk_dropdown_text"
                :halign "end"
                :text "${obj.used}"
              )
            )
            (box
              (label
                :class "disk_dropdown_text"
                :halign "start"
                :text "free:"
              )
              (label
                :class "disk_dropdown_text"
                :halign "end"
                :text "${obj.free}"
              )
            )
          )
        )
      )
    )
  )
)

(defwidget workspaces  []
  (box
    :class "workspaces"
    :spacing 3
    (for obj in hypr
      (eventbox
        :onclick "hyprctl dispatch workspace ${obj.id} > ~/test"
        (label
          :class "workspaces_item"
          :text "${obj.windows}"
        )
      )
    )
  )
)

(include "/home/finley/.config/eww/widgets.yuck")

(defwindow bar
    :class "bar_left"
    :monitor 1
    :geometry
    (geometry
        :x "0px"
        :y "10px"
        :width "3830px"
        :height "30px"
        :anchor "top center"
    )
    :stacking "fg"
    :exclusive true
    :windowtype "dock"
    (box
        :space-evenly true
        (box
            :spacing 10
            :space-evenly false
            (box
                :space-evenly false
                (cpu)
                (ram)
                (disk)
                (workspaces)
            )

            (box
                :space-evenly false
                (volume)
                (app_menu_v2 :apps "${apps}")
            )
        )
        (box
            :halign "center"
            (clock)
        )
        (box
            :width "0"
            :halign "end"
            :space-evenly false
            (power_menu)
        )
    )
)

(defwindow cpu_dropdown
    :class "cpu_dropdown"
    :monitor 1
    :geometry
    (geometry
        :x "5px"
        :y "0px"
        :width "0"
        :height "0px"
        :anchor "top left"
    )
    :windowtype "normal"
    :stacking "fg"
    (box
        (cpu_dropdown)
    )
)

(defwindow ram_dropdown
    :class "ram_dropdown"
    :monitor 1
    :geometry
    (geometry
        :x "65px"
        :y "0px"
        :width "0"
        :height "0px"
        :anchor "top left"
    )
    :windowtype "normal"
    :stacking "fg"
    (box
        (ram_dropdown)
    )
)

(defwindow disk_dropdown
    :class "disk_dropdown"
    :monitor 1
    :geometry
    (geometry
        :x "127px"
        :y "0px"
        :width "0"
        :height "0px"
        :anchor "top left"
    )
    :windowtype "normal"
    :stacking "fg"
    (box
        (disk_dropdown)
    )
)
`

### LINKED ISSUE #992: Widget got deallocated
Since starting using eww, I've always had the error message "Couldn't upgrade reference, widget got deallocated" filling the log, but I never bothered with it because it didn't stop it working and it didn't cause any problems, but after having my laptop running for an extending period of time, I noticed sddm's wayland-session log (eww is launched via hyprland running `eww daemon` on start)
taking up all of my disk space

What's causing this error message and is there any way I can get rid of it

### PR DESCRIPTION
**Pull request by w-lfchen**
## Description
i hate state.

this pr aims to close #992 and close #794
there are architectural issues which cause the behavior described in the issue

basically, the `CustomWidgetInvocation.scope` field is only set once and then used for the scopes of children widgets. since it is never updated, it will never change, but this is needed when variables update.

## Additional Notes
this should be tested well to prevent introducing a regression here.
## Checklist
- [x] I added my changes to CHANGELOG.md, if appropriate.
  *i don't think this is noteworthy enough*
- [x] I used `cargo fmt` to automatically format all code before committing
- [x] clean up warnings that result from the changes

### CODE REVIEW

File: crates/eww/src/widgets/build_widget.rs [hunk 1]
```diff
@@ -288,6 +288,9 @@ fn build_children_special_widget(
     gtk_container: &gtk::Container,
     custom_widget_invocation: Rc<CustomWidgetInvocation>,
 ) -> Result<()> {
+    // open a new scope for the children
+    // TODO this might be unnecessary, evaluate whether we can just use the calling_scope
+    let scope = tree.register_new_scope("children".into(), Some(calling_scope), calling_scope, HashMap::new())?;
```
Comment (w-lfchen) [inline crates/eww/src/widgets/build_widget.rs:293]: initial idea: register a new scope for the children

**Comment by w-lfchen** [comment]
currently, all children are in the same scope.
it might be better to create a new scope for every child

**Comment by rtoijala** [comment]
Very nice to see such a quick response :). I finally had time to test this MR.

This breaks at least the following case:

```
(defwindow broken
  :monitor 0
  (widg :v "foo"))

(defwidget widg [v]
  (wrap
    {v}))

(defwidget wrap []
  (box
    (children)))
```

Trying to open `broken` fails with this message:

```
INFO  eww::app        > Opening window broken as 'broken'
Action failed with error: failed to open window `broken`

Caused by:
    Variable v not in scope
```

Without the changes in this MR, the window opens and displays "foo".

**Comment by w-lfchen** [comment]
@rtoijala thank you so much for your testing!
i've updated some things (everything here is pretty hacky), and now your example works!
the following config seems to work as well:
```
(defwindow broken
  :monitor 0
  (box "test"
    (widg :v var)))

(defwidget widg [v]
  (wrap
  {v}))

(defwidget wrap []
  (box
    (for dummy in var
      (box
        (children)))))
```
please try to break things again, and thanks again for your cooperation!

**Comment by w-lfchen** [comment]
i'll have to see whether i can investigate #675 as well, but it doesn't seem to be related

**Comment by elkowar** [comment]
Has this been working? I haven't had the chance to test this extensively, but if this has been working for you, I'd be down to merge it and worst case just revert if error reports come up

**Comment by w-lfchen** [comment]
i was unable to find any issues with my config

**Comment by elkowar** [comment]
that sounds great! Then I'll merge, and we'll see how it goes! Thanks a lot
